name: Workflow Commands
on: [push]

jobs:
    testing-wf-comms:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missign semicolon"
