name: Workflow Commands
on: [push]

jobs:
    testing-wf-comms:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missign semicolon"
            - name: Setting an error message with params
              run: echo "::error title::notice title, file=app.js",
            - name: Setting an error message with params
              run: echo "::error title::debug title, file=app.js",
            - name: Setting an error message with params
              run: echo "::error title::warning title, file=app.js",
